### ISSUE TITLE
Please don't ignore me please help Unofficial help wanted 🙏🙏

### ISSUE THREAD

**Issue by Saikatsaha1996** [p2k/gw2-discord-webhooks#1]
Cgminer install on termux I got error how can I slove it just for testing my gpu hash rate 
![Screenshot_2021-05-19-02-19-09-726_com termux](https://user-images.githubusercontent.com/72664192/118725577-c1e5fd80-b84d-11eb-9b17-f2f21a1edc34.jpg)

Please please help me please

**Comment by p2k** [comment]
This issue is completely unrelated to this project. Please try somewhere else.

If I had to guess, though, it might be related to your shell. It could be that you use zsh, so try to use bash instead while configuring and compiling this.
